### ISSUE TITLE
v1.5 has a clean task which mean I cannot upload the build output

### ISSUE THREAD

**Issue by wardourdigital** [HubSpot/hubspot-cms-deploy-action#19]
I have a git action as follows:

```
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          npm install
          npm run build-prod
      - name: HubSpot Deploy Action
        uses: HubSpot/hubspot-cms-deploy-action@v1.5
        with:
          src_dir: dist
          dest_dir: hubspot-theme
          portal_id: ${{ secrets.hubspot_portal_id }}
          personal_access_key: ${{ secrets.hubspot_personal_access_key }}
```

## Issue
In version 1.4 this worked fine by allowing me to build the project in my action then uploading the final output folder.

v1.5 appears to clean the folders upon which when the action to upload to HubSpot runs, the built theme folder is "missing"!

## Expected Result
My built folder is not deleted and can be found by the hub spot action to be uploaded to the account.
